### ISSUE TITLE
我在tensorflow1.8的环境使用pb的相关代码没有问题，但是我在1.12版本/1.11版本就会出现下面的问题，怎么半？

### ISSUE THREAD

**Issue by Arthur-Shi** [DetectionTeamUCAS/Faster-RCNN_Tensorflow#24]
Traceback (most recent call last):
  File "./Faster-RCNN_Tensorflow/testwww.py", line 106, in <module>
    'dataSet/matrixtime/lear/whole_image_data/train_test_split_json/1/lier_val1.json')
  File "./Faster-RCNN_Tensorflow/testwww.py", line 55, in test
    img = graph.get_tensor_by_name("input_img:0")
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3666, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3490, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3532, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'input_img:0' refers to a Tensor which does not exist. The operation, 'input_img', does not exist in the graph."

**Comment by Arthur-Shi** [comment]
然而我打印出来是有这个节点的

**Comment by Arthur-Shi** [comment]
修改 gfile的导入路径就好了， from tensorflow.python.platform import gfile
